### ISSUE TITLE
(Plesk) extension fails to install, unstated php requirements

### ISSUE THREAD

**Issue by Kelvin-Ninja** [jxcore/jxcore#132]
After some head banging, it appears that the Plesk extension install quietly fails unless php 5.4 is installed. My server has Plesk 11.0.9, and php 5.3.
Install appeared to have worked, but I get a blank screen if I try to manage the extension.  This line is in the plesk log:  FastCGI-stderr: PHP Parse error:  syntax error, unexpected '[' in /usr/local/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php on line 322

Attempts to uninstall the extension get this error: 
Unable to remove the JXcore Plesk Extension for Node module: Executing /usr/local/psa/admin/plib/modules/jxcore-support/scripts/pre-uninstall.php failed:

I assume my only choice is to find a way to install 5.4, without breaking plesk.

**Comment by spirospolitis** [comment]
Same problem here, with Plesk 11.0.9

**Comment by ktrzeciaknubisa** [comment]
Sorry to hear that. We still haven't gone below 11.5.30. However it seems that 11.0.9 has a lot of [updates](http://download1.parallels.com/Plesk/PP11/parallels-plesk-panel-11-linux-updates-release-notes.html) so maybe it is worth to check if you have them? But event so I cannot guarantee, that this will solve the problem.

**Comment by ktrzeciaknubisa** [comment]
We've marked the JXcore extension to work with 11.5.30+ (as stated at [download page](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support)) so the issue should not show up anymore, as extension will not be even installed on platforms with lower Plesk version number. 

If we ever come back to the subject in order to open support for lower versions, I'll let you guys know about it.
