### ISSUE TITLE
jxcore Plesk v Beta-0.2.3.7 only https

### ISSUE THREAD

**Issue by thebinaryartist** [jxcore/jxcore#170]
I am using ssl via the plesk jxcore panel. Its just working fine, but i want that all request to the http site are redirected to https, or to disable http completely. Is there any way to reach this? Thanks for your help.

I have tried Setting up a https Server in node (disabled SSL in Plesk JXcore Panel):
```
var express = require("express");
var fs = require('fs');

var options = {
  key: fs.readFileSync('data-key.pem'),
  cert: fs.readFileSync('data-cert.pem')
};

var app=express();
var server = require('https').Server(options, app);

var eventEmitter;

app.set('view engine', 'jade');
app.set('views', __dirname + '/views');
app.use(express.static(__dirname + '/public'));

function start() {
    eventEmitter=emitter;
    
    app.get('/', function(req, res){
        res.render('site.jade');
    });
    
    app.get('*', function(req, res){
        res.status(404).render('404.jade');
    });

    server.listen();
}

exports.start = start;
```
In this case I get a 403 Forbidden from the Apache Server.

**Comment by ktrzeciaknubisa** [comment]
Hi, thanks for the question. Generally it's best to leave ssl processing to the nginx, so your app creates only http (non ssl) server and nginx will do the rest once you leave SSL option enabled in JXcore Plesk extension. I understand that you have tried also this way.

Now, to disable http (or redirect http -> https), you could provide some extra directives for nginx on domain's configuration page. I was trying to find an example for you, and this is what I came with:

```nginx
if ($scheme = http) { 
    rewrite ^ https://$server_name$request_uri? permanent; 
}
```
Please adjust this to fit your needs.

However, when I was just about to submit the domain's form, I faced a bug in JXcore extension - the parsing error (related to `\n` characters and auto-appending semi colon) , so I went down to fix it. It is ready now, but I guess it will be available for download only after the weekend. In a meantime, you could try this hack:

```nginx
if ($scheme = http) { rewrite ^ https://$server_name$request_uri? permanent; } gzip_proxied any;
```

The point here is to have it all in one line and also (since semicolon would be added at the end of it - after closing curly bracket - making the syntax invalid) I added simply anything, like *gzip_proxied any;* (because double semicolon `;;` apparently is not a problem).

I tested this in my environment and http redirection works. I hope it will work for you as well.

**Comment by thebinaryartist** [comment]
Your solution is working perfectly for me. Thank you very much.

**Comment by ktrzeciaknubisa** [comment]
Hi, the Plesk team has just published updated version of [JXcore Plesk Extension for Node 2.5.1](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). Nginx directive issue is resolved there, so you don't need those hacks proposed here anymore.
