### ISSUE TITLE
Discuss: Why SpiderMonkey? Why not JavaScriptCore?

### ISSUE THREAD

**Issue by data-wiz** [jxcore/jxcore#186]

**Comment by Ben007** [comment]
How about;
- JavascriptCore's LGPL license
- Did you heard an app banned from AppStore because of partially used webkit? I know many.. Let me remind you, JavascriptCore is a part of webkit. 

I don't know any technical point though :+1: for SpiderMonkey decision. ( performance + number of target platforms, ES6 features )

**Comment by obastemur** [comment]
Let me start with a reminder. One of the JXcore's critical missions is to extend Node.JS's capabilities. 

That means;
- iOS (both SpiderMonkey, and iOS have this option) 
- Windows ARM / RT (I would like to see a node app running PI-2 Windows 10 ARM) I believe the best bet here is SpiderMonkey. Latest interpreter works very smooth. (BTW; anybody remembers QT webkit for winRT ? no..)
-  PowerPC etc.. (SpiderMonkey rocks!)
-  ASM.JS (SpiderMonkey)
-  More ES6 (SpiderMonkey)

I must be the first person running a node.js server application on an ios device. On my iphone 6, jxcore can handle several thousands of requests per second. Dont you think the performance is more than enough ? Remember, JXcore can utilize all the available cores on a mobile device.

Extra Bonus: The great SpiderMonkey developer team. I got all my questions are answered very quickly. When you rely on a JavaScript engine in node.js scale, you need this support though! 

Perhaps JavaScriptCore's developers would also help us to achieve this goal but I didn't go that far with JavaScriptCore engine.

The current architecture of JXcore lets us easily adding another JavaScript engine into action but I don't know any significant reason for having JavaScriptCore dependency. 

If you know any, feel free to share. I would like to hear that!

**Comment by jsbee** [comment]
@obastemur would you say SpiderMonkey has a better public interface than JavaScriptCore ? 
can we consider this as a reason?

**Comment by obastemur** [comment]
I wouldn't say that. I spent enough time with JavaScriptCore and the engine interface is very clear. V8 engine has very nice features for embedders. I had to implement some V8 like features into SpiderMonkey in order to have all the core features are working. JavaScriptCore has other sets of problems (in terms of having everything node.js needs) but details are not important anymore.

**Comment by urbien** [comment]
the main question is - will Apple allow SpiderMonkey based app into the App Store? Perhaps if it is compiled into binary with LLVM (I know you are working on it).

**Comment by obastemur** [comment]
@urbien SpiderMonkey doesn't have a problem on App Store. Because it's have an interpreter mode. There are so many applications on app store already using that.

**Comment by urbien** [comment]
I am really glad to hear it! What apps can you point me to?

**Comment by Ben007** [comment]
SpiderMonkey looks like the only option for node then. If you hack into JavaScriptCore and change it, you should use it as a dynamic library (because of it's license). But Apple App store kick the dynamic library out. Without hacking into JavaScriptCore, you can't possibly run node. It's like chicken-egg dilemma.

**Comment by obastemur** [comment]
@urbien hundreds or thousands of cocos2d-js games. I knew some AAA games also using it but I don't 100% remember the names.

I think the point here is clear after all. Closing.
