### ISSUE TITLE
I am not a C/C++ developer but I’d love to get involved. How can I contribute to JXcore?

### ISSUE THREAD

**Issue by data-wiz** [jxcore/jxcore#196]

**Comment by ktrzeciaknubisa** [comment]
Thanks! Any contribution is more than welcome!

Well, you can run tests on your platforms and see which of them fail. Some of the bugs will need only JavaScript skills to get fixed. You can take a look at [testing](https://github.com/jxcore/jxcore/blob/master/doc/TESTING.md) document to see how to run tests.

You can [fork](https://github.com/jxcore/jxcore/fork) this repository, make there changes (which you would like to propose) and then create a pull request, so we can verify and eventually merge into sources.

**Comment by data-wiz** [comment]
What about documentation? Do you need any help with documentation. I also do a lot of technical writing and documentation in my day job. I can help you with that.

**Comment by ktrzeciaknubisa** [comment]
Well, it came to me once to check at some point whether documentation still reflects how the features work, because when we were doing some changes in the code to deliver fast bug fixes (and development in general), the documentation might not have been always as often updated. 

Apart from that however, I have nothing particular on my mind at the moment.

You are welcome to propose any of your ideas/improvements/contribution :)
