### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by dariusc93** [jxcore/jxcore#199]
I have been interested in JXCore since last year but since it is now open source I notice it is still using v0.10.36. Will this be the version JXCore will use during its lifetime or does it plans to update to use the latest stable version of Node.js in the future? 

I also would like to know more about how will JXCore use LLVM for native application development or will that only be for android and ios? I did remember hearing it was a side project which is one thing that got me interested in JXCore, but If this also does continue on for numerous of platforms, will there be a chance to have the packaging of the executable file decreased so it wouldnt be a 20MB to 40MB+ file for a small server that wouldnt be more 5MB (including node modules)?

**Comment by obastemur** [comment]
the answer for the first question (node.js update) https://github.com/jxcore/jxcore/issues/176 

we dropped llvm work in favor of embedding SpiderMonkey and Duktape into core. Unfortunately LLVM approach doesn't make app size smaller for many reasons. JXcore already runs (almost perfectly) on iOS, and Android in addition to many other platforms. Very soon we are expecting to support WinRT and IBM PowerPC architectures. 

We are totally open to suggestions (since jxcore is now open to everyone). BTW, the packaged binary size should be dropped significantly. Get the sources from this repo and try. Let me know!

We would really appreciate if you can open the discussions (one by one) with an appropriate title.
