### ISSUE TITLE
Node.js + io.js + jxcore?

### ISSUE THREAD

**Issue by micnic** [jxcore/jxcore#204]
Node.js and io.js are going to merge https://github.com/iojs/io.js/issues/978
Are there any plans to merge jxcore with the two projects?

**Comment by ukadakal** [comment]
io.js fork was created by a number of core Node developers and because of their dissatisfaction with the slow progress of the project and its lack of open governance. So by no means it was due to technical differences. Technical direction of io.js is not too different from that of Node.js but at a very accelerated rate. 

On the other hand, JXcore project started because of technical differences where we wanted to run Node on mobile and IoT devices. This is not possible with V8 engine. Node.js project is fully committed to V8 and has no intention of adding another JS engine. That's the reason why we rewrote a significant portion of the core and created a proxy layer to handle swappable JS engine architecture. Hence, it would be extremely difficult to merge JXcore with Node.js or io.js. But I don't think neither Node.js nor io.js want to go in mobile/IoT direction. So I don't see them willing to merge with JXcore.

But we'd love to hear the opinions of the Node community on this matter as we really like to run this project with an open governance model similar to what io.js has.

**Comment by micnic** [comment]
Thanks for the answer, now I understood jxcore position. From my side, I'd like to see the possibility to swap the JS engine in node.js / io.js, that's why I was interested in jxcore. I appreciate your work, thanks for another awesome JS environment.

**Comment by obastemur** [comment]
@micnic thanks for the question. I assume @ukadakal gave the answer. closing this issue

**Comment by jeffbuhrt** [comment]
The JXcore idea is kind cool. They support the same codebase, now multithreaded. JXcore claims also to have builtin monitoring and recovery. ALSO JXcore offers embedded. I am going to try it with the two prototypes I am currently building. Overall without much production experience with JXcore it seems like the winner.

**Comment by ktrzeciaknubisa** [comment]
@jeffbuhrt Nice to hear that, even on closed thread :) Thanks!

**Comment by brodybits** [comment]
I want to mention something else that does not seem to be really documented. It is possible to run native Node.js addons on JXCore as well, as long as they support Node 0.10.x (along with other possible gotchas).

**Comment by obastemur** [comment]
@brodybits thanks in advance!
