### ISSUE TITLE
Android isn't building for me

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#220]
I cloned the depot today and followed https://github.com/jxcore/jxcore/blob/master/doc/Android_Compile.md. I'm using Elementary OS. The config script ran fine but the compile script failed with:

```shell
In file included from ../src/node.h:45:0,
                 from ../src/public/../jx/commons.h:6,
                 from ../src/public/../jxcore.h:5,
                 from ../src/public/jx.cc:4:
../src/public/jx.cc: In function 'void JX_StartEngine()':
../src/public/jx.cc:115:46: error: 'res' was not declared in this scope
   warn_console("JXcore engine is started\n", res);
```

The full failed build output is available at https://gist.github.com/yaronyg/7c59decd81756fca08cc

The bug appears to have been introduced in this commit - https://github.com/jxcore/jxcore/commit/ee76db427b677387c65ef7d5fe2ce5fa8cfad661

res was originally set to the output of LoopOnce but this was removed and so now res isn't defined.

I'm not sure if the fix is to get rid of res or to have it set. I'm way too lazy right now to figure out how to single step through the C code. So for now I just define it as it used to be, as the output of LoopOnce. I'm not submitting it as a PR because I'm not sure if that is the right outcome.

In the meantime though the more interesting question is that the Android build couldn't build after this check in. I take it this means there is no continuous integration to prevent build breaks? Just curious because I'm depending on master branch to be reasonably stable (at least build-able).

**Comment by martinies** [comment]
same for debug build. https://github.com/jxcore/jxcore/pull/221 should take care of it.  I do agree with @yaronyg on continuous build integration but I don't think it's a necessary thing for master. Though master branch always means the latest (not stable or anything else).

Do you need a hand on continuous build and test integration  ?

**Comment by obastemur** [comment]
We have so many targets and it's a big task to test master for every single of them on each commit. I've activated back the travis-ci for base V8 and SM builds. For Android and iOS builds, yml needs a small update but the problem is that travis gives an error when the log file is bigger than 4Mb. So far, I didn't want to disable 'unused variable` warning. What do you think ? If we disable this warning, for sure there will be some room for other build tests.

**Comment by yaronyg** [comment]
I think the key thing here is expectations more than even code.

As someone writing against JXCore we want to understand where we go for 'last known good'. Most open source projects I work with use master for this. Dev work happens in separate branches and when they are known good then (and only then) are they PR'd into master.

If you don't want to use master that way, it's fine, but we should have a branch somewhere which is explicitly known to work. And by 'known to work' I mean passing all tests. So ideally this is something you would sick Travis on, ideally running in parallel.

But I will say that for projects like PouchDB, doing a PR to master is a pain. It can take hours in some cases to get past Travis/Salsa Labs. But that's because they are only using the free accounts so they don't get much in the way of resources. But this is only done for the master. Master is the last step in the process so in practice it isn't that bad.

But, however you do it, it would be really good to have a branch we know is 'known good'. We'll make sure to synch out of there unless we have a good reason not to.

**Comment by ktrzeciaknubisa** [comment]
@yaronyg Thank you. You have your point and I agree with you. However let's remember, that it's just 2 weeks from our initial open source release. We wanted that release so much (exactly to meet the expectations of many people waiting for this - since you've mentioned about 'key thing') that we decided to make it even if it wasn't entirely bug-free and was suffering stability issues. Now we would like to bring it into the 'known good' first (we're very close to it) and after that I believe we're going to make a branch.

**Comment by obastemur** [comment]
Agree with everyone :) As @ktrzeciaknubisa said, as soon as we clear the minor bugs (only few left), we will have a branch for it. Indeed, @yaronyg 's let's keep a 'dev` branch for unstable stuff sounds also good and it's one of the common approaches. I'm in between. Still, It feels like we don't need to change it. Our current approach works for original node repo so it should work for us.
