### ISSUE TITLE
Need a command-line option to display JS Engine info

### ISSUE THREAD

**Issue by soapdog** [jxcore/jxcore#259]
Hey,

Now that jxcore can be built with V8 and Spidermonkey it would be great to have a way to display what is the current js engine built in the running version. We have --version and --nodeversion it would be great to have something like --jsengineversion that output both the engine used and the version info.

**Comment by obastemur** [comment]
sounds nice. I have '-jsv' in mind. any more suggestion ?

**Comment by ktrzeciaknubisa** [comment]
Since we talk about this, I have few general ideas:

1. `-v` and `--version` stands for the same. Why don't we add in the same manner `--jxversion` in addition to `-jxv`?
2. as for the engine, both could exists simultaneously: `--jsengineversion` and `-jsev` (maybe js**ev** corresponds more to **e**ngine **v**ersion than js**v**?), or
   - `-jsv` and `--jsversion` - do we need to use the "engine" word? or
   - `-ev` and `--engineversion` - do we need to use "js" notation? I mean, if we speak about engine, we mean JavaScript engine, right? 

***
Do we have `--nodeversion`? 

```bash
$ jx --nodeversion 
Error: unrecognized flag --nodeversion
```

**Comment by obastemur** [comment]
@ktrzeciaknubisa sounds good. no need for --nodeversion.

**Comment by obastemur** [comment]
https://github.com/jxcore/jxcore/commit/42efc6236d3ed332cf17bb853a4eaa7c77a60e36 takes care of this issue.
