### ISSUE TITLE
test jxcore doesn't cleanup

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#286]
testing jxcore specific api with `sudo tools/test.py jxcore` leaves a garbage behind.

**Comment by ktrzeciaknubisa** [comment]
I've found only some monitor logs left behind. 

There were also folders with name starting from **\_auto\_** prefix and **tmp_jx**, but they are coming from *test/run.js* rather than *tools/test.py*. There were useful for further test inspection, after the test failure. Now I've changed the behavior and they will be removed by default. There's still an option to keep them if needed: `-nc` switch (see help for [test/run.js](https://github.com/jxcore/jxcore/tree/master/test#testrunjs) ).

If you don't use the `test/run.js` much and you want to get rid of *tmp_jx* and *\_auto\_* folders, you can call once: `jx test/run.js clean`.

Are there any other leftovers, that I've missed?

**Comment by obastemur** [comment]
Using jxcore to test jxcore is not an option sometimes. Consider I'm depending on python test.py all the time.

**Comment by ktrzeciaknubisa** [comment]
> sudo tools/test.py jxcore leaves a garbage behind.

It was happening mostly when a command was interrupted (CTRL-BREAK) or timeouted. In such cases some of test units did not have chance to perform a cleanup, since `process.on('exit')` was not called. Those test cases are catching the signals now and should be able do the proper cleanup.
