### ISSUE TITLE
require not supported in JX_Evaluate

### ISSUE THREAD

**Issue by kmgkv** [jxcore/jxcore#301]
If the script passed to JX_Evaluate has a require() statement in it, then it fails to run and returns :
<b>ReferenceError: require is not define</b>

Is this is by design, so does that mean that require statement is not supported in script being passed to JX_Evaluate?

**Comment by obastemur** [comment]
JX_Evaluate by design evaluates the script on the global context. Global context doesn't have a require, __dirname etc. 

There is a way to use require anyways. Please check [this](https://github.com/jxcore/jxcore/tree/master/test/native-interface/test-require) sample test code for native interface. Hope it works for you.

**Comment by kmgkv** [comment]
Thanks obastemur, i'll try this on latest trunk, I think the code which I have built on my dev machine doesn't have process.requireGlobal() defined..... while running script it says: 
<b>TypeError: process.requireGlobal is not a function...</b>

Will update here once I try with the latest trunk
Thanks for your prompt response!

**Comment by obastemur** [comment]
It doesn't have. See the highlighted line from (this link)[https://github.com/jxcore/jxcore/blob/master/test/native-interface/test-require/test-posix.cpp#L9] Test's main file defines that explicitly.

**Comment by kmgkv** [comment]
Ohh ya i see, my baad 😀. Thanks, will try it

**Comment by kmgkv** [comment]
Hi obastemur,
Really appreciate your quick response and logical explanation!!! It works....
