### ISSUE TITLE
Plesk extension Nginx static files

### ISSUE THREAD

**Issue by purepear** [jxcore/jxcore#323]
Hi,
i just installed this extension and was wondering if i can use Nginx to serve static assets instead of express-static.
My structure is sth like
httpdocs/code/index.js (application code)
httpdocs/code/public (/js /css /fonts /img & htmls)
httpdocs/code/public/uploads ---symlink to -- httpdocs/uploads/

I'm deploying with git and using post-update hook
I'd like everything in httpdocs/code/public to be served gzipped from Nginx (not sure if it will work for 'uploads' symlink)
Can you help me with example nginx directive

Also is there vulnerability deploying code in httpdocs/code ... should my code be outside httpdocs
I think it'll be very useful for others .. maybe a blog post on that
Thanks!

**Comment by obastemur** [comment]
@ktrzeciaknubisa this is something maybe we can add into plesk interface ? Mark the folders that you want to deliver with nginx directly.

**Comment by ktrzeciaknubisa** [comment]
In general, by adding specific declaration to domain's `nginx directives` field you should be able to serve static files with nginx. However we've just found out that this will not work for extension v0.2.5, as there is not `root` directive defined for a domain. 

We've prepared an update for the extension, which supports newly released JXcore 0.3.0.0 and also this issue is resolved there.

The update should be available on Plesk's website this week. We will inform when it happens.

The starting point for static serving from *httpdocs/code/public* would be probably something like this:

```js
location /code/public {}
```

**Comment by ktrzeciaknubisa** [comment]
Alright, the new extension update is already available #285 . 

Static files served by nginx are supported. @purepear Please let us know if that works for you.

**Comment by ktrzeciaknubisa** [comment]
I'm closing this, since it is already implemented. Anyone please feel free to reopen in case of any further problems.

**Comment by purepear** [comment]
10x @ktrzeciaknubisa :)
