### ISSUE TITLE
(Plesk) How to set env vars

### ISSUE THREAD

**Issue by ryanbuiltthat** [jxcore/jxcore#394]
I'm using the JXcore extension on Plesk 12. Is there any way to set enviornment variables with this for node?

**Comment by obastemur** [comment]
@ryanbuiltthat From the Panel right? AFAIK no. 

Why don't you set NODE_ENV from OS's configuration file instead ?

**Comment by ryanbuiltthat** [comment]
Can those variables be scoped down to a domain? I'm sorry I'm unfamiliar
with NODE_ENV

**Comment by ktrzeciaknubisa** [comment]
> Can those variables be scoped down to a domain?

Not really.

Are you sure, that you need env variables in first place? App args are not enough for your scenario?

**Comment by ryanbuiltthat** [comment]
Well I need to use `export` when I deploy my app. For example:

`export PORT=8080`

So doesn't that set a Node environmental variables? I could be using the
wrong terminology.

**Comment by obastemur** [comment]
On a single server, setting ENV per domain is not a good, safe, stable approach. Why you are setting the port at all ? We don't allow a node app on plesk using any other port but the on defined by Plesk.

**Comment by ktrzeciaknubisa** [comment]
@ryanbuiltthat Yes, `export PORT=8080` would also be also readable by node app. However, as @obastemur said, setting the port for app running under Plesk would be useless, since we override port defined by a user.

But if you really need an env variable per domain for some other purpose, you may try to set it up on your app, e.g.:

```js
process.env.MyVar = "value";
```

This may work, since env variables are taken from environment on app startup and put into `process.env`. "May" work, because that may depend from the app structure.

**Comment by ryanbuiltthat** [comment]
Thanks for the suggestion. It took care of most of the variable by defining it in the app. The app is built with meteor and needs the database URL define before the app is started.

**Comment by ktrzeciaknubisa** [comment]
Does it mean that this works for you?

**Comment by ryanbuiltthat** [comment]
Haven't had a chance to try it. It's not really the port I need to set
since yes, using Plesk it'll be taken care of anyways. What I need to set
is the URL to the DB and the SMTP URL specific to the app. I'm hoping I can
test this out today. The DB URL Needs to be defined before the app starts
so I'm unable to set that in-app.

**Comment by maxfriedmann** [comment]
Hi @ryanbuiltthat,
I had the exact same problem and would also like to have the possibility to set environment variables for the spawned node processes. 

For the time being I fixed this problem by just writing the necessary variables into the main.js file. Of course that is not a good way of dealing with this, rather a nasty hack. But it works. 

1. upload your meteor bundle to the httpdocs folder printed by jxcore
2. open main.js
3. add your env settings at the top of the file so that it looks like this :  
  ```javascript
// The debugger pauses here when you run `meteor debug`, because this is 
// the very first code to be executed by the server process. If you have 
// not already added any `debugger` statements to your code, feel free to 
// do so now, wait for the server to restart, then reload this page and 
// click the |â–¶ button to continue.

process.env.MONGO_URL="mongodb://localhost:27017/mymeteordbname";
process.env.ROOT_URL="http://mymeteorapp.somethingcool.com";

process.argv.splice(2, 0, 'program.json');
process.chdir(require('path').join(__dirname, 'programs', 'server'));
require('./programs/server/boot.js');
   ```

I also think it's not very nice from meteor itself to not provide any other possibility to set these variable from outside. Would be so easy to solve...

**Comment by ktrzeciaknubisa** [comment]
In fact, since each app is spawned, we may add a way to provide env variables to the single process. I'm marking this as todo item.

**Comment by ryanbuiltthat** [comment]
Thanks @maxfriedmann ! Meteor needs to know where mongo is at before the app starts so I can see why that from the meteor point would be tricky but I agree that there needs to be a better way to manage env variables. I'll give this a shot, you may have just vanquished my nightmares of late! It's been terrible trying to get things working through plesk.

**Comment by ktrzeciaknubisa** [comment]
We've implemented support for env vars per domain's app in Plesk. Anynone want to test it before official release? The development version is [here](https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk.zip).

**Comment by ryanbuiltthat** [comment]
Awesome! Thanks!

On Tue, Jul 7, 2015 at 2:59 PM, Krzysztof Trzeciak <notifications@github.com

**Comment by ktrzeciaknubisa** [comment]
You're welcome. Any feedback/opinions much appreciated.

**Comment by ryanbuiltthat** [comment]
Sorry for the delay in feedback. There's not much to say other than this worked perfectly! Thanks again

**Comment by ktrzeciaknubisa** [comment]
Thank you.

The JXcore 0.2.7 extension for Plesk is now officially [published](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). After the installation, it is recommended to upgrade JXcore to 0.3.0.5.

We have gathered the most important changes and put them into our blog post: [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/).
