### ISSUE TITLE
(Plesk12 jxcore extension) noting happen after click "OK" at agreement page.

### ISSUE THREAD

**Issue by koichi-sato** [jxcore/jxcore#410]
I installed jxcore extension 2.6 for Plesk12, then click "OK" at agreement page but nothing happen.
I check the panel.log and there is PHP Warning,
"[20-Jun-2015 16:49:59 ] Exception: PHP Warning: fopen(https://jxcore.s3.amazonaws.com/0303/jx_rh32v8.zip): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
; File: /usr/local/psa/admin/plib/modules/jxcore-support/controllers/IndexController.php, Line: 898
"
so I did access the url https://jxcore.s3.amazonaws.com/0303/jx_rh32v8.zip, and without SSL connection. But I can not access to the file.
How can indexController.php access to the file?
Thank you.

**Comment by ktrzeciaknubisa** [comment]
Well, that;s because unfortunately at the moment we don't provide precompiled binaries for Red Hat x32. The list of available platforms is on JXcore [downloads](http://jxcore.com/downloads/) page. This reveals, that we should implement checking of target platform during installation of plesk extension.

**Comment by koichi-sato** [comment]
Sorry for my search-less issue, I checked avaialbe platform on page you mentioned.
Many thanks for your response.
