### ISSUE TITLE
Trying to run JXCore on Plesk 12.0.18 Update #53 Centos 6.5 - Doesn't seem to work 

### ISSUE THREAD

**Issue by kpturner** [jxcore/jxcore#425]
The panel pops up with terms and conditions, to which I have to respond by clicking the OK button.  It then says “Please Wait” and that is it.  Nothing else.   What am I missing?

Example:  http://screencast.com/t/od3FrheCkMtm

Thanks

**Comment by ktrzeciaknubisa** [comment]
Well, cannot say much, except that there's something wrong :) Which extension's version are you trying to install? Has php log registered something? You may also try to enable [PHP browser reporting](http://download1.parallels.com/Plesk/Doc/en-US/online/plesk-extensions-guide/index.htm?fileName=71114.htm), co we can find out more.

**Comment by kpturner** [comment]
I am installing the version that comes in the Plesk Extensions Catalog, so that is version 0.2.6.

PHP 5.3.3-40.el6_6

I must confess I have no idea where to look for the PHP log via the Plesk GUI

**Comment by ktrzeciaknubisa** [comment]
I don't think you can access extension's log via Plesk GUI (only domain's log as far as I know). Do you have root access to the machine? if yes, the mentioned link [PHP browser reporting](http://download1.parallels.com/Plesk/Doc/en-US/online/plesk-extensions-guide/index.htm?fileName=71114.htm) might help you.

Also, which architecture is your Centos? If it's x32, then the problem is known: we provide only x64 JXcore binaries for that platform (http://jxcore.com/downloads/).

**Comment by kpturner** [comment]
OK I think it is 32bit.  Thanks.

I have managed to install node and npm now via SSH.

**Comment by ktrzeciaknubisa** [comment]
You may still try to build JXcore by yourself, then give it to Plesk and this will work, too. Plesk will not be able to download it, but there is a backdoor to provide own compiled JXcore binary for Plesk.

**Comment by kpturner** [comment]
OK thanks
