### ISSUE TITLE
Autoremove doesn't seem to be working

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#429]
I am using JXCore v Beta-0.3.0.3

I issued:

```
 jx install --autoremove "*.gz"
```

One of the packages in package.json was leveldown ^1.3.0 (we also had leveldown-mobile ^1.0.7) as well as pouchdb ^3.6.0. Both leveldown and pouchdb install our old friend semver (leveldown also installs packed.tar.gz).

I was expecting autoremove to take care of this but it did not.

**Comment by ktrzeciaknubisa** [comment]
Thanks! Same as #428

**Comment by sreesharp** [comment]
Also, when I used this --autoremove with -g switch, I get the following error
The --autoremove option is not supported with -g or --global switch.

**Comment by ktrzeciaknubisa** [comment]
This is not an error, just the information :) The feature is disabled mostly for safety reasons.

**Comment by sreesharp** [comment]
I didn't get the safety part. We are asking to remove the gz only from the module that we are installing. Right?  It is not touching the other global module anyway.  Since our module is not yet available in npm public repo, we are depending on the global installation.

**Comment by ktrzeciaknubisa** [comment]
>  It is not touching the other global module anyway.

True, but `jx install` may also overwrite existing same global module that was previously installed. In that case removal would take place.

Also the `--autoremove` option was added mostly to help reducing packages sizes in scenarios where node_modules are packed into e.g. mobile apps. Since we assumed, that globally installed modules will rather not be included into that, we disabled `--autoremove` support for `-g`.

However this is an open subject and we may probably unlock it if is really needed.

**Comment by sreesharp** [comment]
Alright. We are using the "jx install -g" to install thali node modules, and eventually these files will be going as part of mobile apps. Currently thali is not available in npm public repo due to the JXCore binary dependency.@obastemur is aware of this problem. 
[Thali_CordovaPlugin](https://github.com/thaliproject/Thali_CordovaPlugin) will be installing the thali modules to global by a cordova plugin hook, and thali developers should be able to develop and deploy the app without much difficulties.
So we really need the -g support, so that thali app developer don't have to manually remove those *.gz files from the global repository.

**Comment by obastemur** [comment]
@ktrzeciaknubisa I'm also +1 on supporting `-g` for `--autoremove`

**Comment by ktrzeciaknubisa** [comment]
Hi guys. The `--autoremove` support is enabled to work with `-g` switch. It's on 0.3.0.5 branch. The next step will be to make `jx install path/to/package.json` working. However I'm thinking that the best will be to move entire autoremove logic out from JXcore (`_jx_install.js`) and put into `deps/npm` which gets downloaded on `jx install`. @obastemur What do you think?

**Comment by obastemur** [comment]
Sounds good
