### ISSUE TITLE
Why forking not supported in native application, how to ensure embedded app threads restart

### ISSUE THREAD

**Issue by ruffrey** [jxcore/jxcore#457]
Hi, jxcore is really cool so far but I am trying to understand why I am getting this error when doing a standard `cluster.fork()`.

```
forking a child process is not supported for embedded applications. Try multithreaded tasks Error: forking a child process is not supported for embedded applications. Try multithreaded tasks
```

Looking at the source, it seems this was intentional:

- https://github.com/jxcore/jxcore/blame/master/lib/child_process.js#L515

I have been trying to get multithreading working for a simple net server, but it only restarts dead threads a few times and then the entire application shuts down. I have not had this problem with normal node cluster.

Why was this exception added? But perhaps more importantly, is there a reason why threads would not restart after a few times?

```javascript
function method(args) {
    process.title = 'kval_worker_' + process.threadId;
    console.log('kval worker', process.threadId, args);
    setTimeout(function () {
        throw new Error('Whoopsie daisy');
    }, 5000 * (Math.random() + 1));
    process.keepAlive();
    process.on('restart', function (restartCallback) {
        console.log('subprocess restart event', process.threadId);
        restartCallback();
    });
}

jxcore.tasks.setThreadCount(args.workers);
jxcore.tasks.runOnce(method, args);
```

**Comment by obastemur** [comment]
```
function method(args) {
  process.title = 'kval_worker_' + process.threadId;
  console.log('kval worker', process.threadId, args);
  setTimeout(function () {
    throw new Error('Whoopsie daisy');
  }, 5000 * (Math.random() + 1));
  process.keepAlive();
  process.on('restart', function (restartCallback) {
    console.log('subprocess restart event', process.threadId);
    restartCallback();
  });
}

setInterval(function(){},1000);
//jxcore.tasks.setThreadCount(args.workers);
jxcore.tasks.runOnce(method, {a:1});
```

Sample above should work. If there is no keepAlive marker at any moment (in case all the threads are down) the process will be shutting down. `setInterval` above will be holding process. 

As for the cluster support for embedded apps, we do not see a reliable way to expose any node specific features to embedded apps. Once you embed the JS files into an executable, that process is not going to accept any node or JS engine command line parameters.

**Comment by ktrzeciaknubisa** [comment]
>  I am getting this error when doing a standard cluster.fork()

One of the first reasons, why forking and spawning was disabled for native applications (`cluster.fork()` calls `child_process.fork()` which i tun calls `child_process.spawn()`) is that once we have a native app, probably we don't have a jx installed. Spawn uses `process.execPath` for spawning which is `jx` for JavaScript apps (and jx packages). Since they both require jx installed, there is no problem with spawning. 

For native apps, `process.execPath` is the `./app` itself (or `app.exe` on Windows) but this is not a jx and it cannot perform spawning or forking. 

However I think that we could add a feature for those, who want to deploy native apps together with separate jx instalaltion - if `jx` is available in $PATH (and we could also check if -jxv version is same as app's `process.jxversion` but that's maybe not necessary) - the we could allow forking and spawning. How about that?

**Comment by ktrzeciaknubisa** [comment]
One extra note: my idea applies to forking in general (forking of .js or .jx files) made inside native apps but not forking **of** native apps. So the `cluster.fork()` would still not work. 

But even here I think we could add a support, too. We can easily check, if the module which is just about to be forked is a native app and in that case we can spawn it instead of jx with module argument.

**Comment by ruffrey** [comment]
@ktrzeciaknubisa that would be wonderful.

**Comment by ktrzeciaknubisa** [comment]
The commit 8bc120cb09deb411bb061b9d878ffa697e47f8de allows you to call `cluster.fork()` for native packages.

**Comment by ruffrey** [comment]
awesome!
