### ISSUE TITLE
Jxcore native module nodegit

### ISSUE THREAD

**Issue by orbatschow** [jxcore/jxcore#490]
When i run this script :

```
var Git = require("nodegit");

Git.Clone("https://github.com/nodegit/nodegit", "nodegit").then(function(repository) {
  console.log(repository);
});
```

with the command "node index.js" everything works fine and it prints {} as exptected to the screen,
however, when i compile it into a native package about 10 seconds there is no response after executing it and after that, it throws this error:

```
/tmp/node/node_modules/nodegit/lib/nodegit.js.jx:24
var _AnnotatedCommit_fromFetchhead = _AnnotatedCommit.fromFetchhead;
                                                     ^
TypeError: Cannot read property 'fromFetchhead' of undefined
    at Object.<anonymous> (/tmp/node/node_modules/nodegit/lib/nodegit.js.jx:24:54)
    at Module._compile (module.js:518:26)
    at Object.Module._extensions..jx (module.js:1653:7)
    at Module.load (module.js:345:36)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:377:17)
    at require (module.js:395:17)
    at Object.<anonymous> (/tmp/node/index.js.jx:1:11)
    at Module._compile (module.js:518:26)
    at readX (module.js:1284:5)
```

The compiling and executing platform is the same, there is no system change in between these two steps.

**Comment by ktrzeciaknubisa** [comment]
Hi, to be honest this code prints nothing for me, no matter if I run `node index.js` or `jx index.js` not to mention about packaging. Which platform are you using?

**Comment by Synturas** [comment]
I run this script on fedora20. The point is, it works when executing it with nodejs, but when I turn it into a native package with:
```
jx package index.js MyApp -native
```
the above error is printed and the git clone doesn't work.

**Comment by ktrzeciaknubisa** [comment]
Ok, I was able to see that error when running a native package, however I suspect that there is something more here and fixing that error will not help us much.

* on MacOSX even `node index.js` didn't work for me (neither `jx index.js`). That is not a good thing about nodegit. However only here i saw your exception after I created a native package.
* on Fedora `node index.js` worked but `jx index.js` didn't (and this is first step to be checked before testing native package)
* please take a look at size of MyApp native package. It is 68 MB on my MacOSX due to nodegit module embedded. Are you sure you want to have that big file? Maybe leaving the *node_modules* out of package would work for you?:

    ```bash
jx package index.js MyApp -native -slim "node_modules"
```
    But then you need to deploy this folder together with MyApp native package.

One more thing: how did you install nodegit? Did you use `npm install` or `jx install`? If you want to use native module with JXcore, better use `jx install` .

**Comment by ktrzeciaknubisa** [comment]
Have some more info about this:

> when i compile it into a native package about 10 seconds there is no response after executing it

Yeap, that's because entire 68 MB package contents gets unpacked during this time.

> and after that, it throws this error: TypeError: Cannot read property 'fromFetchhead' of undefined

The error can be avoided by marking .node files as extractable:

```bash
$ jx package index.js MyApp -native --extract-what "*.node" --extract-app-root
```

However even after skipping the error I was not able to receive any output.
