### ISSUE TITLE
JXP: keep everything in binary format

### ISSUE THREAD

**Issue by plika** [jxcore/jxcore#508]
Current design keeps the structure in a fat JSON which is an absolute time taker. We may introduce a pure binary without an addition base64 /  compressor level.

**Comment by ktrzeciaknubisa** [comment]
I've taken a measure to implement this and came up with success.

However I needed to disable previous compression methods (*jxutils_wrap*: `_cmp()` / `_ucmp()` ) because I'm operating only on buffers now, while `_cmp()` receives only strings (unlike `_ucmp()` which accepts buffers on the other hand). 

If someone could give me a hand on this (make `_cmp()` and eventually `CompressString()` accept also buffers) I could use that.

**Comment by obastemur** [comment]
Let me take care of that ;)

**Comment by ktrzeciaknubisa** [comment]
@obastemur Let me know when it's ready :) Than I can go on with the packages binary format.

**Comment by karaxuna** [comment]
@ktrzeciaknubisa is this what you need? https://github.com/jxcore/jxcore/pull/630

**Comment by ktrzeciaknubisa** [comment]
Can't really say. It's closed and 0 commits :)

**Comment by karaxuna** [comment]
@ktrzeciaknubisa Sorry, I closed that PR, take a look at this one: https://github.com/jxcore/jxcore/pull/631

**Comment by ktrzeciaknubisa** [comment]
Closing the ticket as this is already implemented starting from 0.3.1.0.
