### ISSUE TITLE
Inconsistent case handling behavior

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#566]
I ran a test using JXcore on OS/x where a require had the value 'foo/bar/Blah' where foo was installed and bar is a directory under foo and Blah is the specific javascript file to load.

The problem is that the file on disk actually has the name 'blah' not 'Blah'

On OS/X (which as far as I know is a case sensitive system) jx ran the require without problem. But on Android it failed because of casing.

Insanity will result if we can't rely on consistent behavior for the node code across platforms! I'd even think it was fine to have a special 'mobile' mode for desktop where it will act like mobile, including failing on improperly cased names.

**Comment by ktrzeciaknubisa** [comment]
You haven't mention how node behaves on your OSx ? I'll bet same way as jx.

They say that OSx filesystem may be either case-sensitive or insensitive. http://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not

Mine probably is case-insensitive, because both `node` and `jx` are working ok no matter if I require Blah or blah.

**Comment by yaronyg** [comment]
Yeah. Fixing this would be a nightmare. Oh well.
