### ISSUE TITLE
Running Ogar multithreaded

### ISSUE THREAD

**Issue by Qasimmodo** [jxcore/jxcore#595]
https://github.com/OgarProject/Ogar

A fully functional open source Agar.io server implementation, written in Node.js. Ogar is designed to be used with the latest Agar.io client.

 How do I run this multi-threaded, because when I do it creates multiple instances of the server and the players get split up on different instances. So there would end up being like 10 in each instance (core).

**Comment by karaxuna** [comment]
Each thread has it's own memory. You shall share memory between them using jxcore.store.shared

**Comment by Qasimmodo** [comment]
So, what would I type in my SHH to get it to run as 1 instance but multithreaded.

**Comment by ktrzeciaknubisa** [comment]
Generally you run JXcore multi-threaded e.g. like this:

```bash
$ jx mt-keep Ogar
```

> How do I run this multi-threaded, because when I do it creates multiple instances of the server

so how did you run it multi-threaded before?

**Comment by Qasimmodo** [comment]
The problem is, i'm using it in a gaming circumstance so therefore it creates multiple instances of the server all on 1 port and splits all the players up onto different cores.

**Comment by ktrzeciaknubisa** [comment]
> multiple instances of the server all on 1 port

Just for clarity: you mean instances of http/https server, not instances of a process? Because with JXcore you have only one process, but yes, each thread runs a server on same 1 port. 

How else would you expect it to work? Each player served by different threads?

You can also start the Ogar in one separate thread by using `jxcore.tasks` : 

```js
jxcore.tasks.addTask(function() {
   process.keepAlive();
   require(`./Ogar`);
});
```

That gives you only one server instance, only one subthread for all players. Not much of multithreading benefit.

**Comment by Qasimmodo** [comment]
How do I edit jxcore.tasks, sorry, I am a slight noob. :P

**Comment by ktrzeciaknubisa** [comment]
> How do I edit jxcore.tasks ...

@Qasimmodo What do you mean by "edit" ?

My example can be saved into e.g. *start.js* and executed with `jx start.js`. But I'm still not sure if this is what you are looking for :)

**Comment by Qasimmodo** [comment]
This is what happens when I use jx mt-keep Ogar

http://prntscr.com/8qjf5w

**Comment by Qasimmodo** [comment]
@ktrzeciaknubisa Also, with the 

jxcore.tasks.addTask(function() {
   process.keepAlive();
   require(`./Ogar`);
});

I get the error: http://prntscr.com/8qjirr

**Comment by ktrzeciaknubisa** [comment]
> This is what happens when I use jx mt-keep Ogar

And why does it bother you that it starts twice (once per each thread) ? 

> I get the error: http://prntscr.com/8qjirr

Obviously you need to use quote or single quote around "./Ogar" (not tilde).

**Comment by Qasimmodo** [comment]
@ktrzeciaknubisa As I said previously, it creates multiple sessions doesn't it? And I was experiencing the players getting split up.

**Comment by ktrzeciaknubisa** [comment]
Ok, I see your point now. I didn't think in session-like terms (thus players sharing sessions, or session separation). 

So we came back to the entry point and probably best wold be to follow @karaxuna advice. You may need to modify Ogar sources and change the access to GameServer fields (.clients, .noded, etc., etc.) - save them into [jxcore.store.shared](http://jxcore.com/docs/jxcore-store.html#jxcorestoreshared) and also read from there. 

So for example instead of [this.clients = [];](https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L22) you may try to define it as getter/setter which reads from/saves to `jxcore.store.shared`, and so on.

**Comment by Qasimmodo** [comment]
Ok, thanks for your help :)
