### ISSUE TITLE
Leveldown module did not self-register error

### ISSUE THREAD

**Issue by deadlyfingers** [jxcore/jxcore#597]
When trying to run a node project with **Leveldown** on localhost I'm getting an error **"Module did not self-register"** with `bindings.js`. I'm using jxcore version v 0.3.0.7 on Mac OS X 10.10.5 

Here's the error snippet from the console log:
```
www/jxcore/node_modules/leveldown/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
```

**Comment by ktrzeciaknubisa** [comment]
Did installation of leveldown go successfully? Did you use `jx install` ?

**Comment by deadlyfingers** [comment]
Yes, and I also tried `jx install leveldown`
Here is the error running the app using `jx app.js` in localhost:
```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /app/www/jxcore/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /app/www/jxcore/node_modules/pouchdb/node_modules/leveldown/build/Release/leveldown.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

**Comment by ktrzeciaknubisa** [comment]
This error indicates, that you were using SpiderMonkey version of JXcore. Am I right? Please try with V8.

**Comment by ktrzeciaknubisa** [comment]
Also, I see that leveldown is a dependency of pouchdb in your error log. So in case if you have installed it with `npm install pouchdb`, I advise you to use `jx install pouchdb`. Then installing leveldown separately will not be necessary.

**Comment by ktrzeciaknubisa** [comment]
Below is my understanding of the situation. Please correct me if I'm mistaken:

1. you have installed PouchDB using npm. That exact command also used the npm to install leveldown as dependency under *node_modules/pouchdb/node_modules/leveldown/*
2. Now even if you `jx install leveldown` it will not help you much, since it will be installed in different folder: *node_modules/leveldown*, but pochdb will still use its own directory under  *node_modules/pouchdb/node_modules/leveldown/*.
3. so at this point either you remove *node_modules/pouchdb/node_modules/leveldown/* to force pouchdb to use a leveldown installed with JXcore, or better remove entire *node_modules* and reinstall pouchdb with JXcore entirely. By doing so, I haven't found any problem.

**Comment by obastemur** [comment]
@deadlyfingers shall we close this issue ?

**Comment by deadlyfingers** [comment]
Giving this a final run through today...

**Comment by ktrzeciaknubisa** [comment]
Thank you too, @deadlyfingers .
