### ISSUE TITLE
fs.readFile() does not handle exceptions properly with extensions

### ISSUE THREAD

**Issue by gcampax** [jxcore/jxcore#634]
If a fs extension (such as the one introduced by jxcore-android/jxcore-cordova) throws an exception in readfilesync, mostly likely NOENT, readFile() crashes instead of calling the callback with the exception, which lets the caller handle it.

**Comment by ktrzeciaknubisa** [comment]
Personally I'm aware of this and I was even warning about this before. In fact, as far as we talk about jxcore-cordova, this was even fixed by [commit](https://github.com/jxcore/jxcore-cordova/commit/aafac4b54ba34ca2c78cc55b1f7b36eca92ac5df) and then reverted back. Here is some [discussion](https://github.com/jxcore/jxcore-cordova/commit/f95c3f87568ee59efe0693c777cbab092ac1f1fd#commitcomment-13313160). 

But I believe this is dependent on how the extension method itself is implemented. Not much to do with extensions internals (*fs.js*). Am I mistaken @gcampax ?

**Comment by gcampax** [comment]
Well, if your extension interface is defined as "read the file or throw an error" - because that's what the sync methods do, then it's up to the async wrapper to turn "throw an error" into "call the callback with an error"

**Comment by ktrzeciaknubisa** [comment]
You're right @gcampax . The above commit takes care of it internally. However to have this patch in jxcore-android/jxcore-cordova, you need to wait for new binaries release (or compile by yourself).

Thanks!

**Comment by gcampax** [comment]
Oh I'm compiling everything from source so it's not a problem.

Thanks for addressing this!
