### ISSUE TITLE
More detailed stack traces from threads 

### ISSUE THREAD

**Issue by milonas115** [jxcore/jxcore#655]
restarting thread 2 due to error TypeError: Cannot read property 'index' of undefined

-------------------------------------

How do I get errors happening inside threads to show full stack traces without having to try/catch everything.

**Comment by ktrzeciaknubisa** [comment]
Well, I thought, that `uncaughtException` for the thread would work, but apparently it doesn't (and never did  - I've checked with "ancient" JXcore 0.2.3.7)

```js
var method = function() {

  process.on('uncaughtException', function(ex) {
    console.log('ex', ex);
  });

  var s = nonexistentFunc();
}
jxcore.tasks.addTask(method);
```

I thing it's a need to add at least exception message (if not full stack trace) to [process.on('restart')](http://jxcore.com/docs/jxcore-feature-internal-recovery.html#internal-instance-recovery) listener.

Because once you'll subscribe for that event, you no longer receive the error, which normally would be:

```bash
ReferenceError: nonexistentFunc is not defined
```

**Comment by obastemur** [comment]
Actually the `uncaughtException` only kicks in when the error is happening after the initial context load. In this case, if you would run the throwing part inside a `setTimeout` etc. you would have the event call.

**Comment by obastemur** [comment]
jxcore 0.3.1.0 will be printing stack trace for the errors on global context.
