### ISSUE TITLE
ios: --embed-leveldown fails compiling

### ISSUE THREAD

**Issue by obastemur** [jxcore/jxcore#658]
Spidermonkey proxy fails for `--embed-leveldown` ios cross build. Probably it also fails for Android too. (0.3.1.0)

**Comment by obastemur** [comment]
This was a local dev-env issue.

**Comment by ktrzeciaknubisa** [comment]
Well, I still get the following for android:

```bash
$ sudo ./build_scripts/android_compile.sh ~/android-ndk-r10d --embed-leveldown

make[1]: *** [/[...]/jxcore/out/Release/obj.target/leveldown/deps/leveldown-mobile/src/batch_async.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/[...]/jxcore/out/Release/obj.target/leveldown/deps/leveldown-mobile/src/batch.o] Error 1
make: *** [jx] Error 2
compilation aborted for arm target
```

And it works without `--embed-leveldown`.

**Comment by ktrzeciaknubisa** [comment]
I take it back. Looks like I used wrong leveldown-mobile branch. 

I needed to pull leveldown-mobile separately, because my *deps/leveldown-mobile* was empty. Now when I switched to [leveldown-mobile/tree/791effbccf114ec5b449aa467fe451098ed7da86](https://github.com/Level/leveldown-mobile/tree/791effbccf114ec5b449aa467fe451098ed7da86) (as linked on *jxcore/deps/*) it compiles fine.
