### ISSUE TITLE
Simple HTTP server leaks memory in jxcore

### ISSUE THREAD

**Issue by scriby** [jxcore/jxcore#794]
I was doing some simple load testing for fun on an OpenWRT device running jxcore. I kept noticing that the jx process would continue to consume memory until it crashed during the load test. I was also able to reproduce the same results running jxcore on my MBP. I just installed jxcore today, so I assume I am running the latest version (`jx --version` prints v0.10.40).

The same test runs without issue under node v0.10.40. Memory usage gets up to around 16 MB, then stops growing.

Reproduction steps:

1. Run the following script with jx:

```
var http = require('http');

http.createServer(function (req, res) {
  res.end('Hello hello hello');
}).listen(9000);

console.log('listening on port 9000');
```

2. Run a simple load test

```
npm install loadtest
cd node_modules/loadtest/bin
./loadtest.js -n 100000 -c 1 -k http://localhost:9000/
```

As someone investigating jxcore for the purpose of running node.js code on low spec devices, these results are somewhat disconcerting.

Thanks,

Chris

**Comment by obastemur** [comment]
@scriby I wouldn't call it leak. When you loadtest, you don't give any time to GC and unfortunately the device you are running on has a very limited memory. So you can try `jxcore.tasks.forceGC` periodically to ensure you force GC and free some of the memory.

**Comment by scriby** [comment]
Here's some more details:

I didn't run a single load test. I ran the load test command, waited a little while, then ran another. No matter what load sizes I chose I never saw any memory reclaimed between tests.

I added the following code to the script:

```
setInterval(function() {
  console.log('GC')
  jxcore.tasks.forceGC();
}, 10000);
```

I don't see any difference in memory usage. In both environments, memory continues to climb while the load test is running. When the load test is not running the memory is not reclaimed.

**Comment by scriby** [comment]
I tried the same test with jxcore running spidermonkey. While it uses up quite a bit more memory initially (a little over 100 MB), memory usage appears to be more stable over time.

**Comment by obastemur** [comment]
@scriby It's normal as for now JXcore doesn't set stack for OpenWRT targets specially.

IMO, targeting 16Mb board, I would anyway use jxcore/node as a service/deamon. If you need help on this let us know. If you know this part and can contribute some docs here, we would really appreciate

**Comment by scriby** [comment]
I'm not targeting a 16 MB board. I'll have around 100 MB.

I feel like I'm failing to make my point though. I initially noticed the problem on Openwrt, but I see the exact same behavior on my MacBook Pro.

The only explanation I have for the behavior I am seeing is a memory leak. What evidence do I need to provide to convince you of the same?

 I am super excited about jxcore and it solves a very real problem for me. I really, really want to use it. Thanks for your time and help!

**Comment by scriby** [comment]
<img width="676" alt="memory" src="https://cloud.githubusercontent.com/assets/815188/12537214/876a0118-c287-11e5-9ea5-1d69f99dfcda.png">

The above graph shows memory usage over a 5 minute period. I ran a series of 4 load tests, with a pause in between (that's the flat area on the graphs).

The node process stabilizes around 33 MB. The jxcore-v8 one continues to grow over time. The spidermonkey one is all over the place, but seems to still be stable.

**Comment by obastemur** [comment]
@scriby the growth is in actual cache. I will try to create some time and make memory oriented caching configuration.

**Comment by scriby** [comment]
How high should I expect the cache to grow? I've tested it up to 100 MB before, but haven't had the patience to keep going.

**Comment by scriby** [comment]
On a side note, I was able to get plain node v0.10.40 running on openwrt. I performed the same benchmark and memory usage is similar to my desktop (grows to around 30 MB then stops).

So now I am wondering what benefit I'd have from using jxcore over plain node. Feel free to reply to me by email (scriby at gmail dot com) if you don't want to carry on this conversation here.

Thanks again for your time!

Chris

**Comment by obastemur** [comment]
![ins](https://cloud.githubusercontent.com/assets/4390745/12541472/c65407da-c317-11e5-9688-5ad888c1f56d.png)

@scriby What I could do is to share attached SS above for the test application given next;

```
var http = require('http');

var n=0;
http.createServer(function (req, res) {
  res.end('Hello hello hello');
  
  if (n%6 == 0)
    jxcore.tasks.forceGC();
    
  n %= 1000;
  n++;
}).listen(9000);
``` 

Rest is clear on SS. Memory grows stops at 49 Mb. This number may change for SM/V8 OS/App etc. 

Also run clang leak/address sanitizer / valgrind on ubuntu machine without problem.  

We force old GC approach for SM due to design of node. Unfortunately v8 and SM are very different (in terms of GC). For example, by default we don't use any upper limit for SM (i.e. GC or Die ) 

Not just GC part. Although JXcore is a fork from Node 0.10.x, streams / tcp etc. parts also partially reimplemented for jxcore. 

Thanks for sharing all these stuff. While I was running several analyzers on the code, saw some places to clean up. 

If you would like to setup similar environment for leak detection, feel free to reach! Memory leaks are hard to catch evils. In case I'm missing something and you may roughly point a leak, I would really appreciate. This is an open work and we could all benefit. 

However for now,  I can't observe it. (tried really hard). 

> Feel free to reply to me by email (scriby at gmail dot com) if you don't want to carry on this conversation here.

We should freely talk everything technical here. 

Closing for now. Thanks again.

**Comment by scriby** [comment]
Thanks for looking into it further. It would still be helpful if there was some way to further restrict the memory so it can work on low-memory devices.
