### ISSUE TITLE
could not fetch message

### ISSUE THREAD

**Issue by staminna** [jxcore/jxcore#912]
Hi

I downloaded the script named jx_install.sh and granted execution permission and runned the file. 

`$ ./jx_install.sh 
JXcore Installation Script for X systems
 
Testing for a BSD distro 
Downloading latest version info 
Could not fetch 
`

This error is in red.
I am using MacOS, current version.

**Comment by jasonkarns** [comment]
That script relies on pulling assets from Amazon S3 buckets. However, those buckets no longer exist (because: http://www.nubisa.com/nubisa-halting-active-development-on-jxcore-platform/). Unless you can find existing precompiled binaries out in the wild, your only real alternative is compiling from source.
